_BASE_: "clip_base.yaml"


MODEL:
  TIMM:
    BASE_NAME: models/convnext_xxlarge/laion2b_s34b_b82k_augreg

DATALOADER:
  DATASET_BS: [1, 4]

OUTPUT_DIR: "./output/convnext_xxlarge_laion2b_s34b_b82k_augreg"
