_BASE_: "clip_base.yaml"


MODEL:
  TIMM:
    BASE_NAME: models/convnext_xxlarge/laion2b_s34b_b82k_augreg

DATALOADER:
  DATASET_BS: [1, 4]
SOLVER:
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 2000
  
OUTPUT_DIR: "./output/convnext_xxlarge_laion2b_s34b_b82k_augreg"
